export enum Bank {
  SBER = 'sber',
  T_BANK = 't_bank',
  ALFA = 'alfa',
  VTB = 'vtb',
  GAZPROM = 'gazprom',
  RAIFFEISEN = 'raiffeisen',
  OTP = 'otp',
  ROSBANK = 'rosbank',
  OPEN = 'open',
  SOVCOMBANK = 'sovcombank',
  MKB = 'mkb',
  PSB = 'psb',
  RSHB = 'rshb',
  DOMRF = 'domrf',
  URALSIB = 'uralsib',
  AK_BARS = 'ak_bars',
  ZENIT = 'zenit',
  ABSOLUT = 'absolut',
  AVANGARD = 'avangard',
  RUSSIA = 'russia',
  SNGB = 'sngb',
  CHELINDBANK = 'chelindbank',
  CENTR_INVEST = 'centr_invest',
  KUBAN_CREDIT = 'kuban_credit',
  ASIA_PACIFIC = 'asia_pacific',
  POCHTA = 'pochtabank',
  ROUND = 'round',
  SBP = 'sbp',
  PHONE = 'phone',
}

export const BankLabels: Record<string, string> = {
  sber: 'Сбербанк',
  t_bank: 'Т-Банк',
  alfa: 'Альфа-Банк',
  vtb: 'ВТБ',
  gazprom: 'Газпромбанк',
  raiffeisen: 'Райффайзенбанк',
  otp: 'ОТП Банк',
  rosbank: 'Росбанк',
  open: 'Банк Открытие',
  sovcombank: 'Совкомбанк',
  mkb: 'МКБ',
  psb: 'ПСБ',
  rshb: 'Россельхозбанк',
  domrf: 'Дом.РФ',
  uralsib: 'Уралсиб',
  ak_bars: 'Ак Барс',
  zenit: 'Банк Зенит',
  absolut: 'Абсолют Банк',
  avangard: 'Авангард',
  russia: 'Банк Россия',
  sngb: 'СНГБ',
  chelindbank: 'Челиндбанк',
  centr_invest: 'Центр-инвест',
  kuban_credit: 'Кубань Кредит',
  asia_pacific: 'АТБ',
  pochtabank: 'Почта Банк',
  round: 'Круглый банк',
  sbp: 'СБП',
  phone: 'Телефон',
}
